[package]
name = "parrot"
version = "0.3.0"
authors = ["aquelemiguel"]
edition = "2018"
description = "A Discord music bot built in Rust"
repository = "https://github.com/aquelemiguel/parrot"
license = "MIT"
keywords = ["discord", "music-bot", "rust"]

[lib]
name = "parrot"
crate-type = ["rlib"]

[dependencies]
dotenv = "0.15"
html2md = "0.2"
rand = "0.8"
regex = "1.5"
reqwest = "0.11"
serde = "1.0"
serde_json = "1.0"
scraper = "0.12"
youtube_dl = "0.6"

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
features = ["builtin-queue", "yt-dlp"]

[dependencies.serenity]
version = "0.10"
features = ["cache", "framework", "standard_framework", "voice", "collector"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
