[package]
name = "parrot"
version = "1.0.1"
authors = ["aquelemiguel"]
edition = "2018"
description = "A Discord music bot built in Rust"
repository = "https://github.com/aquelemiguel/parrot"
license = "MIT"
keywords = ["discord", "music-bot", "rust"]

[dependencies]
dotenv = "0.15"
rand = "0.8"
serde_json = "1.0"

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
branch = "current"
features = ["builtin-queue", "yt-dlp"]

[dependencies.serenity]
version = "0.10"
default-features = false
features = ["cache", "collector", "client", "gateway", "model", "rustls_backend", "unstable_discord_api", "voice"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
