[package]
name = "parrot"
version = "0.1.0"
authors = ["aquelemiguel"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15"
youtube_dl = "0.6.3"
rand = "0.8.4"

[dependencies.songbird]
version = "0.2.0"
features = ["builtin-queue"]

[dependencies.serenity]
version = "0.10"
features = ["cache", "framework", "standard_framework", "voice"]

[dependencies.tokio]
version = "1.0"
features = ["macros", "rt-multi-thread"]
