name: Docker Personal Deployment
on: push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Kill All Docker Containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOYMENTKEY }}
          script_stop: true
          script: containers=$(docker ps -q) \
            if [ ! -z $containers ]; then \
            docker kill $containers; \
            fi
      - name: Deploy with New Image
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOYMENTKEY }}
          script_stop: true
          script: docker run -d --pull "always" --env-file .env ghcr.io/aquelemiguel/parrot:latest
