name: Docker Build Workflow
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: docker build .
