name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.55", "1.56", "1.57"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build Binary
        run: cargo build

      - name: Run Unit Tests
        run: cargo test

      - name: Check minimal versions
        run: cargo update
