name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.55", "1.56", "1.57", "1.58", "1.59"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Build Binary
        run: cargo build --locked

      - name: Build Release Binary
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: cargo build --release --locked

      - name: Run Unit Tests
        run: cargo test

      - name: Run Release Unit Tests
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: cargo test --release --locked
