name: Main Workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", "1.57"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Format Rust Code
        run: |
          rustup component add rustfmt
          cargo fmt --all -- --check

      - name: Lint Rust Code
        run: |
          rustup component add clippy
          cargo clippy -- -D clippy::all

      - name: Build Release Binary
        run: cargo build --release

      - name: Run Unit Tests
        run: cargo test
