name: Main Workflow

on: [push, pull_request]

jobs:
  build:
    name: Build
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", "1.57"]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - name: Repository Checkout
        uses: actions/checkout@v2

      - name: Install toolchain
        id: tc
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal
          components: rustfmt, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v1

      - name: Format Rust Code
        run: cargo fmt --all -- --check

      - name: Lint Rust Code
        run: cargo clippy -- -D clippy::all

      - name: Build Release Binary
        run: cargo build

      - name: Run Unit Tests
        run: cargo test

      - name: Check minimal versions
        run: cargo clean; cargo update; cargo check
