name: Main Workflow
on: [push]
jobs:
  build:
    strategy:
      matrix:
        rust-version: ["1.54", "1.55", "1.56", latest]
    runs-on: ubuntu-latest
    container: rust:${{ matrix.rust-version }}
    steps:
      - uses: actions/checkout@v2
      - run: rustup component add rustfmt
      - run: cargo fmt --all -- --check
      - run: cargo build --release
      - run: cargo test
